### ISSUE TITLE
Narrow requested permissions

### ISSUE THREAD

**Issue by znd4** [jsongerber/thanks.nvim#3]
Could you limit this app's permissions to [starring](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#user-permissions-for-starring) and remove the requested scopes? `:ThanksGithubAuth` is requesting full repo:write privileges, which presumably isn't needed

**Comment by znd4** [comment]
If I have time, I'll try creating a github app and checking if any code changes are needed besides removing the `scopes`

**Comment by jsongerber** [comment]
Thanks for your message.

I actually tried that, GitHub apps let you define fine-grained permissions which include `starring:write`. But it didn't let me use the starred endpoint using device workflow.

Switching to a GitHub OAuth app fixed the problem, but unfortunately it uses scopes which has less permission options.

What I can do is auth with `public_repo` by default, which gives access to more than stars but do not give access to code.

And let users optionally auth with `repo` if they want to star private repos.

Now it uses both by default and I think this is the latter that can be a problem.

Does that seems reasonable to you?

**Comment by znd4** [comment]
Oof, yeah, I see that. And based on [this stackoverflow post](https://stackoverflow.com/questions/76557387/unable-to-star-unstar-a-github-repo-when-using-the-github-api-github-app-integr), it seems like it's been an issue for a while.

Tbh, it's could still be a significant security risk to have full write privileges on public repos, although it's still worth doing

I've also created a ticket with github support, b.c. I'm pretty sure that this is a bug

**Comment by jsongerber** [comment]
Thanks for contacting gh, please let me know if they answer something useful.
I spent some time today trying to make it work again with fine grained permissions without luck.

I also searched how other cli tools were handling access keys and it seems pretty common to just store it in a file, [even GitHub does that](https://cli.github.com/manual/gh_auth_login#:~:text=After%20completion%2C%20an%20authentication%20token,to%20a%20plain%20text%20file.) under certain circumstances.

Without better solution I will close this issue, but please free to reopen if needed.
