### ISSUE TITLE
Github auth commands (curl) fail if neovim is started from nushell.

### ISSUE THREAD

**Issue by chduckie** [jsongerber/thanks.nvim#4]
`curl_command` uses `||`, an operator that is unsupported in nushell.

The idiomatic nushell equivalent would be:
```nushell 
try { <curl_command> } catch { echo "error" }
```

Perhaps the existence of `vim.env.NU_VERSION`, or the value of `vim.env.SHELL`, could inform the command to use?

**Comment by jsongerber** [comment]
Thank you for your report.

I never tried nushell, I'll try to install it one of these days to fix the problem.

I don't know yet if I want to continue using raw curl or if I should maybe switch to a lib to handle different shell and os.

Maybe plenary can help.

I'll comment back when I found a solution.
