### ISSUE TITLE
Feature request: star to specific list

### ISSUE THREAD

**Issue by flexagoon** [jsongerber/thanks.nvim#6]
I'm using lists to organize my GitHub stars:

https://github.com/flexagoon?tab=stars

And I'd like to add all of my nvim plugin to the "I'm using those" list specifically instead of just starting them. Would be great to have a config option for that (if that's possible with the GitHub API)

**Comment by jsongerber** [comment]
Unfortunately GitHub does not yet expose an endpoint to create/edit lists.
You're not the first to ask this feature, so I'll make sure to implement it once this endpoint is available (and that I hear about it).
