### ISSUE TITLE
getting 'only lazy and packer' when using lazy

### ISSUE THREAD

**Issue by hunleyd** [jsongerber/thanks.nvim#7]
After updating this morning, I'm suddenly getting:
> Only Lazy and Packer plugin manager is supported at the moment

even though I *am* using Lazy, and this has been working fine.

**Comment by jsongerber** [comment]
Weird, I tried with your config and could not reproduce.
Thanks.nvim checks if the command `:Lazy` exists to determine if you're using Lazy.

Could you try to run the command `:echo exists(":Lazy")` and tell me the result?

Also, could you tell me the version number of Neovim you're using?

Thanks!

**Comment by jsongerber** [comment]
I tried your whole Neovim config and could reproduce.
For some reason, thanks.nvim seems to be loaded before the `:Lazy` command is registered.
I changed the detection method, could you try if the latest update fixes this?

**Comment by hunleyd** [comment]
I no longer receive the error! And I saw that it did indeed star some repos. Thank you!
